title: Francesco Hrobat # name of the site
author: Francesco Hrobat # name of site's author
email: francesco.hrobat@maths.ox.ac.uk # email of site's author
url:  "https://fhrobat.github.io" # root address of the site
scholar: "https://scholar.google.com/citations?hl=it&user=sB-MFsYAAAAJ"
baseurl: "/website" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
 <div class="row">
  <div class="column">
  <img src="hrobat.jpg" class="img-portrait" alt="portrait">
  </div>
  <div class="column">
  <a href="mailto:francesco.hrobat@maths.ox.ac.uk"> email </a>  <a href="https://fhrobat.github.io"> github </a> <a href="https://scholar.google.com/citations?hl=it&user=sB-MFsYAAAAJ"> scholar </a> <a href="https://arxiv.org/search/math?searchtype=author&query=Hrobat,+F"> arxiv </a> <a href="https://www.linkedin.com/in/francesco-hrobat"> linkedin </a> <a href="https://orcid.org/0009-0002-5304-8107"> orcid </a> <br>
  I am a Mathematics PhD student at University of Oxford, Linacre College. <br>
  I am supported by the Mathematical Institute Scholarship by Oxford Mathematical Institute. <br>
  Previously, I completed my bachelor's and master's degrees at Scuola Normale Superiore of Pisa and University of Pisa. <br> <br>
  My research focuses on <strong>numerical linear algebra</strong>, including parturbation theory, randomized linear algebra and Krylov methods.
  </div>
 </div>
permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "home" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page
  lowercase_titles: false # show titles in lowercase in lists

sass:
  style: compressed
  sass_dir: _sass

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jektex

jektex:
  cache_dir: ".jektex-cache"
  ignore: ["*.xml"]
  silent: false
  macros:
    - ["\\Q", "\\mathbb{Q}"]
    - ["\\C", "\\mathbb{C}"]
