title: Francesco Hrobat # name of the site
author: Francesco Hrobat # name of site's author
email: francesco.hrobat@maths.ox.ac.uk # email of site's author
url:  "https://fhrobat.github.io" # root address of the site
scholar: "https://scholar.google.com/citations?hl=it&user=sB-MFsYAAAAJ"
baseurl: "/website" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: >
  <p class="contacts">
   <a href="mailto:francesco.hrobat@maths.ox.ac.uk">Email</a>
   <a href="https://github.com/fhrobat/" target="_blank" rel="noopener">GitHub</a>
   <a href="https://scholar.google.com/citations?hl=it&user=sB-MFsYAAAAJ" target="_blank" rel="noopener">Google Scholar</a>
   <a href="https://arxiv.org/search/?searchtype=author&query=Hrobat%2C+F" target="_blank" rel="noopener">arXiv</a>
   <a href="https://www.linkedin.com/in/francesco-hrobat" target="_blank" rel="noopener">LinkedIn</a>
   <a href="https://orcid.org/0009-0002-5304-8107" target="_blank" rel="noopener">ORCID</a>
  </p>
  <div class="row">
    <div class="column column--photo">
      <img src="hrobat.jpg" class="img-portrait" alt="Francesco Hrobat, portrait">
    </div>

    <div class="column">
      <div class="column-inner">
        <p>
        I am a Mathematics PhD student at the University of Oxford, Linacre College. I am supported by the Mathematical Institute Scholarship by Oxford Mathematical Institute.
        <br> <br>
        My research focuses on <strong>numerical linear algebra</strong>, including perturbation theory, randomized linear algebra and Krylov methods.
        </p>
      </div>
    </div>
  </div>


permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
goat_counter: "fhrobat" # put your GoatCounter name if you want to use GoatCounter analytics

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "home" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page
  lowercase_titles: false # show titles in lowercase in lists

sass:
  style: compressed
  sass_dir: _sass

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jektex

jektex:
  cache_dir: ".jektex-cache"
  ignore: ["*.xml"]
  silent: false
  macros:
    - ["\\Q", "\\mathbb{Q}"]
    - ["\\C", "\\mathbb{C}"]
