title: Francesco Hrobat # name of the site
author: Francesco Hrobat # name of site's author
email: francesco.hrobat@maths.ox.ac.uk # email of site's author
url:  "https://fhrobat.github.io" # root address of the site
baseurl: "/website" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
 <a href="mailto:francesco.hrobat@maths.ox.ac.uk.com"> email </a>  <a href="https://github.com/fhrobat"> github </a> <br>
 I am Francesco Hrobat a Mathematics PhD student at University of Oxford, Linacre College. <br>
 I am supported by the Mathematical Institute Scholarship by Oxford Mathematical Isntitute. <br>
 Previously. I did my bachelor's and master's at Scuola Normale Superiore of Pisa. <br> <br>
 My research focuses on <strong>numerical linear algebra</strong>, including parturbation theory, randomized linear algebra and Krylov methods.
permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "home" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page
  lowercase_titles: false # show titles in lowercase in lists

sass:
  style: compressed
  sass_dir: _sass

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jektex

jektex:
  cache_dir: ".jektex-cache"
  ignore: ["*.xml"]
  silent: false
  macros:
    - ["\\Q", "\\mathbb{Q}"]
    - ["\\C", "\\mathbb{C}"]
